apiVersion: v1
kind: Service
metadata:
  name: 8seneca-website-service
spec:
  selector:
    app: 8seneca-website
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
